### ISSUE TITLE
postgres-data is missing in .gitignore

### ISSUE THREAD

**Issue by simulieren** [dev-xo/stripe-stack#31]
Hey 👋 
thank you for this great template. I've set it up locally and it just works!
I noticed `postgres-data` is missing in the `.gitignore` and the whole DB was commited on my side. Is this on purpose?

**Comment by dev-xo** [comment]
Hello @simulieren thanks you for reaching on here!
I'm not sure if I understand at all the Issue! 

Guess `postgres-data` is a file / folder? Didn't noticed it on my side working with Postgres, or not sure i'f im missing something! Because in that case for sure should be added into `.gitignore`!

Could you please show me some code / image? Or do a Pull Request with the fix?
I'm XO#9732 in Remix Discord in case you wanna reach me on there.

Thanks you!

**Comment by dev-xo** [comment]
I've updated `remix.init`. Now you should not get `remix.init` folder anymore into your workspace, and the template should not give an error after initializing, complaining about database.

Can you do a fresh `npx create-remix@latest --template dev-xo/stripe-stack`? Set your database and notice me how it goes!

Still need to add `postgrtes-data` to `.gitignore`, but you helped me figure out remix.init folder wasn't removing properly on Postgres version. Thanks you!

**Comment by simulieren** [comment]
@dev-xo I've created a quick PR with the fix. Please feel free to change the PR up, if you feel the need to. 😄 

The `postgres-data` folder is created when starting a local PostgreSQL server with the `docker-compose.yml` that comes with the template. So the folder would only appear, if you develop with a local DB.

To make it work after a shutdown of the container, I had to also alter the `docker-compose.yml` to this configuration:

```yaml
version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data/pgdata

volumes:
  pg-data:
```
